export const historyData = [

    {
        "id": 1,
        "icon": "./img/visa_txt.svg",
        "title": "VISA/RUB",
        "oper_type": "Пополнение",
        "status": 'completed',
        "prihod": "-",
        "rashod": "3.48",
        "valuta": "USDT",
        "komissiya": "0.1",
        "date": "08.03.2023",
        "time": "21:43",
        "rekvisit": "0709683738",
        "note":"Оплата услуг 'О!' ",
    },
    {
        "id": 2,
        "icon": "./img/visa_txt.svg",
        "title": "VISA/RUB",
        "oper_type": "Покупка",
        "status": 'not_completed',
        "prihod": "-",
        "rashod": "3.48",
        "valuta": "USDT",
        "komissiya": "0.1",
        "date": "08.03.2023",
        "time": "21:43",
        "rekvisit": "0709683738",
        "note":"Оплата услуг 'О!' ",
    },
    {
        "id": 3,
        "icon": "./img/visa_txt.svg",
        "title": "VISA/RUB",
        "oper_type": "Блокировка",
        "status": 'blocked',
        "prihod": "-",
        "rashod": "3.48",
        "valuta": "USDT",
        "komissiya": "0.1",
        "date": "08.03.2023",
        "time": "21:43",
        "rekvisit": "0709683738",
        "note":"Оплата услуг 'О!' ",
    },
    {
        "id": 4,
        "icon": "./img/visa_txt.svg",
        "title": "VISA/RUB",
        "oper_type": "Блокировка",
        "status": 'blocked',
        "prihod": "-",
        "rashod": "3.48",
        "valuta": "USDT",
        "komissiya": "0.1",
        "date": "08.03.2023",
        "time": "21:43",
        "rekvisit": "0709683738",
        "note":"Оплата услуг 'О!' ",
    },
    {
        "id": 5,
        "icon": "./img/visa_txt.svg",
        "title": "VISA/RUB",
        "oper_type": "Блокировка",
        "status": 'blocked',
        "prihod": "-",
        "rashod": "3.48",
        "valuta": "USDT",
        "komissiya": "0.1",
        "date": "08.03.2023",
        "time": "21:43",
        "rekvisit": "0709683738",
        "note":"Оплата услуг 'О!' ",
    },
    {
        "id": 6,
        "icon": "./img/visa_txt.svg",
        "title": "VISA/RUB",
        "oper_type": "Блокировка",
        "status": 'blocked',
        "prihod": "-",
        "rashod": "3.48",
        "valuta": "USDT",
        "komissiya": "0.1",
        "date": "08.03.2023",
        "time": "21:43",
        "rekvisit": "0709683738",
        "note":"Оплата услуг 'О!' ",
    },
    {
        "id": 7,
        "icon": "./img/visa_txt.svg",
        "title": "VISA/RUB",
        "oper_type": "Блокировка",
        "status": 'blocked',
        "prihod": "-",
        "rashod": "3.48",
        "valuta": "USDT",
        "komissiya": "0.1",
        "date": "08.03.2023",
        "time": "21:43",
        "rekvisit": "0709683738",
        "note":"Оплата услуг 'О!' ",
    },
    {
        "id": 8,
        "icon": "./img/visa_txt.svg",
        "title": "VISA/RUB",
        "oper_type": "Блокировка",
        "status": 'blocked',
        "prihod": "-",
        "rashod": "3.48",
        "valuta": "USDT",
        "komissiya": "0.1",
        "date": "08.03.2023",
        "time": "21:43",
        "rekvisit": "0709683738",
        "note":"Оплата услуг 'О!' ",
    },
]